### ISSUE TITLE
Featured

### ISSUE THREAD

**Issue by clydde** [paulo-raca/YetAnotherArduinoWiegandLibrary#12]
I think it would be interesting to implement the Methods:

"getCARDNumberString",
"getCARDNumberHEX"
"getCARDNumberInt"

 and the same for the wiegand bits:

"getBitsString",
"getBitsInt"

I think this would greatly facilitate the extraction of CardID to pesones, which is harder for the programming.

**Comment by paulo-raca** [comment]
Yes, that's a good idea

**Comment by paulo-raca** [comment]
By "getBitsString" you expect a string of 0s and 1s?

**Comment by clydde** [comment]
Xdd no, us an error, xdd tksssEl 8 abr. 2019 16:11, Paulo Costa <notifications@github.com> escribió:By "getBitsString" you expect a string of 0s and 1s?

**Comment by paulo-raca** [comment]
What?!

**Comment by clydde** [comment]
getBitsString It is not necessary, it was a mistake when I made Copy & Paste.

**Comment by paulo-raca** [comment]
Same as #13
