### ISSUE TITLE
is possible LED control?

### ISSUE THREAD

**Issue by joztoz** [paulo-raca/YetAnotherArduinoWiegandLibrary#14]
Hello, my reader have also LED, but I have only one wire, please how I can control color of led?
Second wire is marked as a Base, but I dont understand if its tamper or buzzer, I think, there wire marked as LED is for green/red led and buzzer.
Please how can i control it? connected to GND or VCC is not doing anything.
Thank you

**Comment by paulo-raca** [comment]
Unfortunately LED control is not a part of wiegand, this library won't help you.

In fact, I've never seen a reader with this kind of control (although many of them will blink a light or beep automatically).

I'm curious, can you provide details on your device?
