### ISSUE TITLE
Wiegand 32-bit support

### ISSUE THREAD

**Issue by pasleto** [paulo-raca/YetAnotherArduinoWiegandLibrary#25]
Hello,

would it be possible to add support for 32-bit wiegand?

Now it is throwing error, but the card UID is correct.
Card read error: Unsupported message format - Raw data: 32bits / A4DCCC1D

**Comment by paulo-raca** [comment]
Maybe?
But is this a standard format?
I've seen 34 bits used a lot (32 data bits + 2 parity bits), and it works fine. Does your desired format has parity bits, or is it a raw format?

**Comment by pasleto** [comment]
Hi,
I have modified your library to my needs. I have HID iClass SE readers which can output multiple formats, inluding 32bit (LSB or MSB), 56bit, 64bit, etc. some of them are with parity others without.
But i have troubles to support some Legic readers, which output 42 or 58 bits, i dont know now, i dont have these readers already. I thought including 42 and 58 in parity stripping function should work, but legic format reordering some bits in output, so this was not working, obviously. I might play with this, if i get to those readers again.

**Comment by paulo-raca** [comment]
Glad you got it to work, I'm sorry to be a few months late :sweat_smile: 

Just in case, you could use this option to disable the built-in message decoding schemes:
```
Wiegand.begin(/*expected_bits=*/LENGTH_ANY, /*decode_messages=*/false)
```

This way you can receive the raw payloads and implement custom parity checks and decoding.
