### ISSUE TITLE
Not working but reader works on Pi

### ISSUE THREAD

**Issue by bigdavelamb** [paulo-raca/YetAnotherArduinoWiegandLibrary#28]
I have a reader that works on the Raspberry Pi using both these code libraries:

https://github.com/alperenguman/rpi-wiegand-reader

https://gist.github.com/hsiboy/9598741

However when using YetAnotherArduinoWiegandLibrary on my Arduino Uno I am not getting anything back whatsoever. I know this is very vague but not sure what to try as this is my first look at an Arduino

**Comment by paulo-raca** [comment]
Aren't you getting error callbacks either? 😅

Are you sure the pin changes are being captured by your code and wiegand.setPinXState() is being called?

It is possible that you may need to tweak the timeout value for your particular sensor.

Can you give more details on your Arduino board and the wiegand reader you are using?

**Comment by bigdavelamb** [comment]
Hi Paulo

Thanks. No callbacks, nothing whatsoever.  It's an Arduino Uno R3 and it's brand new. I do not think setPinXState is being called. I have tried just running some very simple code just now that checks if the Pin state changes using this (when reading a card):

void setup(){
    pinMode( DIN_PIN, INPUT );
       pinMode( DIN_PIN2, INPUT );
    Serial.begin( 9600 );
     Serial.println("setup");
}

void loop(){
    int value;
    
    value = digitalRead( DIN_PIN );
    if(value!=0)
    Serial.println( value );

    value = digitalRead( DIN_PIN2 );
        if(value!=0)
    Serial.println( value );
    delay( 1 );
}

And I am not getting anything back so I am wondering if my GPIO on the Arduino could be faulty, however if I do  digitalWrite(DIN_PIN, HIGH); in my code it does detect the state has changed on the PIN.

**Comment by paulo-raca** [comment]
Yes, sounds link the board or the wiring are defective.
